### ISSUE TITLE
Requirements out dated

### ISSUE THREAD

**Issue by romain-le-mercier** [PrestaShop/circuit-breaker#37]
Right now the package requires guzzlehttp/guzzle ^5.
Can it be updated to 6.1 so it can be compatible with microsoft/microsoft-graph ?

Thanks.

**Comment by matks** [comment]
Hi @romain-le-mercier unfortunately we cannot because we are using this package in https://github.com/PrestaShop/PrestaShop where guzzle version is frozen to v5 as we follow SemVer. We will only be able to upgrade to guzzle v6 when we release the next version of PrestaShop.

I'm afraid you can only do this in a fork 😞

**Comment by mickaelandrieu** [comment]
Hi @romain-le-mercier,

you may use this library https://github.com/loveOSS/resiliency which is a fork of this one but with updated dependencies.

Note that I'm the former author of the 2 libraries.

Regards

**Comment by matks** [comment]
Closing as the situation has not changed for now.

We are considering the idea of introducing dependency breaking changes in next PS version (1.7.8) because some of our dependencies will need to be updated, even if it introduces BC breaks, as they reach EOL (and security is more important than backward compatibility).
